kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  image: golang:1.11
  environment:
    GO111MODULE: on
  commands:
  - go vet ./...

- name: test
  image: golang:1.11
  environment:
    GO111MODULE: on
  commands:
  - curl -fL https://getcli.jfrog.io | sh
  - mv jfrog /bin/jfrog
  - go test -cover ./...

- name: dryrun
  image: plugins/docker
  settings:
    dry_run: true
    auto_tag: true
    password:
      from_secret: docker_password
    repo: jmccann/drone-artifactory
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: build
  image: golang:1.11
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
  - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    repo: jmccann/drone-artifactory
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master